name = "tokensmatter"
main = ".open-next/worker.js"
compatibility_date = "2026-04-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "tokensmatter"
database_id = "d42a6028-5afb-4449-83a9-23b79c770f06"
preview_database_id = "d42a6028-5afb-4449-83a9-23b79c770f06"
migrations_dir = "migrations"
